PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX dlo: <http://ns.inria.fr/datalens/ontology/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dlt: <http://ns.inria.fr/datalens/thesaurus/>
SELECT * WHERE {

    ?model a dlo:Model ;
        dlo:hasModality dlt:Audio ;
        dc:identifier ?modelName ;
        dcat:landingPage ?modelUrl ;
        ?rel ?resource ;
    	dlo:downloadCount ?downloads .
	
    VALUES ?rel {
        prov:wasDerivedFrom
        dlo:wasTrainedOn
    }
    
    ?rel rdfs:label ?relationship.
    ?resource dc:identifier ?resourceName ;
      a ?type .
    
    VALUES ?type {
        dlo:Model
        dlo:Dataset
    }
    
    ?type rdfs:label ?resourceType .
    
    FILTER (?downloads > 10000)
    
}
