SELECT
  ?genus ?genusLabel
  ?family ?familyLabel
  (COUNT(DISTINCT ?species) AS ?speciesCount)
WHERE {
  ?species wdt:P171* wd:Q25265 .
  ?species wdt:P105 wd:Q7432 .
  ?species wdt:P171 ?genus .

  ?genus wdt:P105 wd:Q34740 .
  ?genus wdt:P171* ?family .
  ?family wdt:P105 wd:Q35409 .

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en".
  }
}
GROUP BY ?genus ?genusLabel ?family ?familyLabel
ORDER BY DESC(?speciesCount)
LIMIT 200
