SELECT ?species ?speciesLabel ?family ?familyLabel ?articleCount WHERE {
  ?species wdt:P171* wd:Q25265 .
  ?species wdt:P105 wd:Q7432 .

  ?species wdt:P171* ?family .
  ?family wdt:P105 wd:Q35409 .

  ?species wikibase:sitelinks ?articleCount .

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en".
  }
}
ORDER BY DESC(?articleCount)
LIMIT 100
