PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dlt: <http://ns.inria.fr/datalens/thesaurus/>
PREFIX dlo: <http://ns.inria.fr/datalens/ontology/>

SELECT DISTINCT *
WHERE {
    ?resource dlo:hasTask dlt:QuestionAnswering ;
    	dcterms:identifier ?resourceName ;
    	dlo:downloadCount ?downloads .
           
    VALUES ?p {
        dlo:hasLibrary
        dlo:hasAcademicArticle
        dcterms:license
        dlo:hasTask
        dlo:hasSubTask
        dlo:hasModality
        prov:wasDerivedFrom
        dlo:wasTrainedOn
    }

    ?resource ?p ?relation .
    
    ?p rdfs:label ?pLabel .
    FILTER(LANGMATCHES(LANG(?pLabel), "en"))
    
    FILTER (?downloads > 10000)
}